
[general]
BROWSER = "chrome"
ELEMENT_OUTPUT_LOG = "user_friendly"
DO_NOT_RESTART = true
SOFT_RESTART = false
SITE = 'https://fix-online.sbis.ru/'
PROXY_ADDRESS = "dts-proxy-outside-squid.dev-dts-proxy-outside.svc.qa1-dpc.k8s.tensor.ru:3128"

[custom]
LOGIN = "Регламент123"
PASSWORD = "Регламент1231"
